# Generated by Django 4.1 on 2022-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
