# Generated by Django 4.1 on 2022-08-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=250)),
                ('serial_number', models.CharField(max_length=250)),
                ('device_timestamp', models.DateTimeField()),
                ('recording_type', models.CharField(max_length=250)),
                ('glucose_value_history', models.CharField(max_length=250)),
                ('glucose_scan', models.CharField(max_length=250)),
            ],
        ),
    ]
