# Generated by Django 4.1 on 2022-08-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='device_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
