# Generated by Django 4.1 on 2022-08-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_alter_reading_device_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='glucose_scan',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='glucose_value_history',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
