# Generated by Django 4.1 on 2022-08-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_alter_reading_glucose_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='glucose_scan',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='glucose_value_history',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
