# Generated by Django 4.1 on 2022-08-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_alter_reading_glucose_scan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-id']},
        ),
    ]
